services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - '8000:8000'
    # bind COPY ./app /code/app and make sure fastapi runs with reload for this CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./app:/code/app
      - ./certificate.pem:/certificate.pem
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
